name: Release plugin

#on: [push]
on:
#  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{github.token}} #required by gh cli
    steps:
      - uses: actions/checkout@v1

      - name: Install packages
        run: composer install --prefer-dist --no-progress --no-suggest --no-dev

      - name: Create plugin archive
        run: tar -czf /tmp/plugin.tar.gz assets src vendor .compatibility.php LICENSE readme.txt $(ls woosms-*)

      - name: Archive contents
        run: tar -tf /tmp/plugin.tar.gz

      - name: Add archive to release
        run: gh release upload ${{github.ref_name}} /tmp/plugin.tar.gz